version: "3"
services:
    api:
      build: .
      depends_on:
        -postgres
      ports: 
        - 8000:8000
      volumes:
        - ./:/usr/usr/app:ro
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      # env_file:
      #   -./.env 
      environment:
        - database_hostname=postgres
        - database_port=5432
        - database_password=Qwerty1234$
        - database_name=fastapi
        - database_username=postgres
        - secret_key="09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
        - algorithm=HS256
        - access_token_expire_minutes=60

    postgres:
      image: postgres
      environment: 
        - POSTGRES_PASSWORD=Qwerty1234$
        - POSTGRES_DB=fastapi
      volumes:
        - postgres-db: /var/lib/postgresql/data
volumes:
  postgres-db:
