name: Build and Deploy Code

# on: [push,pull_request]
# on:
#   push:
#     branches:
#       - "main"
#   pull_request:
#     branches:
#       - "main"

on: [push, pull_request]

jobs:
  job1:
    runs-on: job1:ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to user
        run: echo "hello user"
